spring.profiles.default=local

spring.h2.console.enabled=true

# SQL 스크립트 자동 실행(선택: schema.sql, data.sql 사용 시)
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=none
spring.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.forward-headers-strategy=framework
